package com.jw.holidayguard.dto;

import lombok.*;

@Data
@EqualsAndHashCode(callSuper = true)
public class CreateScheduleRequest extends ScheduleBase {

    // Inherits all fields from ScheduleBase:
    // - String name (validated)
    // - String description  
    // - String country (defaults to "US")
    // - boolean active (defaults to true)
    
    // NO ID field - auto-generated by JPA using @GeneratedValue
}