version: 2.1

orbs:
  maven: circleci/maven@1.4.1

jobs:
  test:
    docker:
      - image: cimg/openjdk:21.0
    steps:
      - checkout
      - run:
          name: Restore Maven Dependencies
          command: mvn dependency:go-offline
      - run:
          name: Run Tests
          command: mvn clean test
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/surefire-reports

  build:
    docker:
      - image: cimg/openjdk:21.0
    steps:
      - checkout
      - run:
          name: Restore Maven Dependencies
          command: mvn dependency:go-offline
      - run:
          name: Build JAR
          command: mvn clean package -DskipTests
      - store_artifacts:
          path: target/*.jar

workflows:
  build-and-test:
    jobs:
      - test
      - build:
          requires:
            - test