package com.jw.holidayguard.dto;

import jakarta.validation.Valid;
import lombok.*;

import java.util.List;

@Data
@EqualsAndHashCode(callSuper = true)
public class CreateScheduleRequest extends ScheduleBase {

    // Inherits all fields from ScheduleBase:
    // - String name (validated)
    // - String description  
    // - String country (defaults to "US")
    // - boolean active (defaults to true)
    
    // NO ID field - auto-generated by JPA using @GeneratedValue
    
    /**
     * Initial rules for this schedule. If not provided, defaults to WEEKDAYS_ONLY.
     * At least one rule is required to make the schedule functional.
     */
    @Valid
    private List<CreateScheduleRuleRequest> rules;
    
    /**
     * Optional initial overrides for this schedule.
     */
    @Valid
    private List<CreateScheduleOverrideRequest> overrides;
}